### PR TITLE
Woodpecker events 1

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
This one also does nothing at all.

**Comment by dessalines** [comment]
Its the woodpecker standard now that every when block needs an event, even if there are other AND conditions.

**Comment by Nutomic** [comment]
I mean the whole ci config isnt running any checks at all.

**Comment by dessalines** [comment]
Yeah, we might add some in the future tho, and it's already added to woodpecker. iirc prettier doesn't play well with weblate, which was a check we used to have on all the translation repos.

**Pull request merged**
